In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
studata = files.upload()

Saving schoolstudents.xlsx to schoolstudents.xlsx


In [ ]:
studf=pd.read_excel('schoolstudents.xlsx')

In [ ]:
studf

Age  Weight (kg)  Height (cm)  Standard
0    17           60          170        11
1     7           25          120         2
2    16           55          165        10
3    18           70          175        12
4     7           25          120         2
5    11           35          140         5
6     8           30          125         3
7    10           33          135         4
8    15           50          160         9
9    14           45          155         8
10   18           70          175        12
11   14           45          155         8
12   12           40          145         6
13    8           30          125         3
14   18           70          175        12
15   15           50          160         9
16   16           55          165        10
17   15           50          160         9
18   16           55          165        10
19    8           30          125         3
20    7           25          120         2
21   18           70          175        12
22   15           50          160         9
23   18           54          162        12

In [ ]:
studf.describe()

Age  Weight (kg)  Height (cm)   Standard
count  24.000000    24.000000    24.000000  24.000000
mean   13.375000    46.750000   151.333333   7.625000
std     4.062688    15.146387    19.837748   3.692678
min     7.000000    25.000000   120.000000   2.000000
25%     9.500000    32.250000   132.500000   3.750000
50%    15.000000    50.000000   160.000000   9.000000
75%    16.250000    55.000000   165.000000  10.250000
max    18.000000    70.000000   175.000000  12.000000

In [ ]:
x=studf.iloc[:,:-1].values  #start to end


In [ ]:
x

array([[ 17,  60, 170],
       [  7,  25, 120],
       [ 16,  55, 165],
       [ 18,  70, 175],
       [  7,  25, 120],
       [ 11,  35, 140],
       [  8,  30, 125],
       [ 10,  33, 135],
       [ 15,  50, 160],
       [ 14,  45, 155],
       [ 18,  70, 175],
       [ 14,  45, 155],
       [ 12,  40, 145],
       [  8,  30, 125],
       [ 18,  70, 175],
       [ 15,  50, 160],
       [ 16,  55, 165],
       [ 15,  50, 160],
       [ 16,  55, 165],
       [  8,  30, 125],
       [  7,  25, 120],
       [ 18,  70, 175],
       [ 15,  50, 160],
       [ 18,  54, 162]])

In [ ]:
y =studf.iloc[:,3:4].values

In [ ]:
y

array([[11],
       [ 2],
       [10],
       [12],
       [ 2],
       [ 5],
       [ 3],
       [ 4],
       [ 9],
       [ 8],
       [12],
       [ 8],
       [ 6],
       [ 3],
       [12],
       [ 9],
       [10],
       [ 9],
       [10],
       [ 3],
       [ 2],
       [12],
       [ 9],
       [12]])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=13)

In [ ]:
x_train.shape

(16, 3)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
s_regression = LinearRegression()

In [ ]:
s_regression.fit(x_train,y_train)

LinearRegression()

In [ ]:
result = s_regression.predict(x_test)

In [ ]:
s_regression.predict([[ 26,  55, 182]])

array([[18.94709502]])

In [ ]:
y_test

array([[ 9],
       [ 2],
       [ 4],
       [ 9],
       [ 8],
       [ 2],
       [11],
       [ 3]])

In [ ]:
result

array([[ 8.92705882],
       [ 1.94      ],
       [ 4.49576471],
       [ 8.92705882],
       [ 7.96588235],
       [ 1.94      ],
       [10.84941176],
       [ 2.90117647]])

In [ ]:
studf

Age  Weight (kg)  Height (cm)  Standard
0    17           60          170        11
1     7           25          120         2
2    16           55          165        10
3    18           70          175        12
4     7           25          120         2
5    11           35          140         5
6     8           30          125         3
7    10           33          135         4
8    15           50          160         9
9    14           45          155         8
10   18           70          175        12
11   14           45          155         8
12   12           40          145         6
13    8           30          125         3
14   18           70          175        12
15   15           50          160         9
16   16           55          165        10
17   15           50          160         9
18   16           55          165        10
19    8           30          125         3
20    7           25          120         2
21   18           70          175        12
22   15           50          160         9
23   18           54          162        12

In [ ]:
error = result-y_test

In [ ]:
error

array([[-0.07294118],
       [-0.06      ],
       [ 0.49576471],
       [-0.07294118],
       [-0.03411765],
       [-0.06      ],
       [-0.15058824],
       [-0.09882353]])